
CREATE TABLE `questions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `question` text NOT NULL,
  `option_a` varchar(255) NOT NULL,
  `option_b` varchar(255) NOT NULL,
  `option_c` varchar(255) NOT NULL,
  `option_d` varchar(255) NOT NULL,
  `correct_option` char(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB;

INSERT INTO questions (question, option_a, option_b, option_c, option_d, correct_option) VALUES
('What does PHP stand for?', 'Personal Home Page', 'Preprocessor Hypertext', 'Programming Hypertext Preprocessor', 'Pre Hypertext Preprocessor', 'B'),
('Which PHP statement is used to output text?', 'print', 'echo', 'display', 'show', 'B'),
('What is the correct way to start a PHP block?', '<?php', '<?=', '<php', '<?PHP', 'A'),
('Which of the following is a superglobal variable?', '$_POST', '$_SERVER', '$_COOKIE', 'All of the above', 'D'),
('What is the default file extension for PHP files?', '.php3', '.html', '.php', '.ph', 'C'),
('How can we get the IP address of the client in PHP?', '$_SERVER[\'SERVER_ADDR\']', '$_SERVER[\'REMOTE_ADDR\']', '$_SERVER[\'HTTP_HOST\']', '$_SERVER[\'CLIENT_ADDR\']', 'B'),
('What is the use of the `isset()` function in PHP?', 'Check if a variable is set', 'Check if a variable is empty', 'Check if a variable is null', 'None of the above', 'A'),
('Which function is used to include a file in PHP?', 'include()', 'require()', 'Both A and B', 'None of the above', 'C'),
('What is the scope of a variable declared outside a function in PHP?', 'Local', 'Global', 'Static', 'None of the above', 'B'),
('How do you declare a constant in PHP?', 'define()', 'const', 'constant', 'Both A and B', 'D'),
('Which function is used to check if a file exists in PHP?', 'file_exist()', 'file_exists()', 'is_file()', 'exists_file()', 'B'),
('What is the purpose of `explode()` function in PHP?', 'Split a string into an array', 'Join array elements into a string', 'Find a substring in a string', 'None of the above', 'A'),
('Which function is used to get the length of a string in PHP?', 'length()', 'strlen()', 'size()', 'strlength()', 'B'),
('What is the purpose of the `session_start()` function in PHP?', 'Start a new session', 'End a session', 'Store session variables', 'Destroy a session', 'A'),
('Which method is used to send a form data using GET method in PHP?', '$_POST', '$_GET', '$_FORM', '$_REQUEST', 'B'),
('What is the output of the following code? echo 3 + "5 cars";', '35', '8', '3', 'Error', 'B'),
('How do you create an array in PHP?', 'array()', 'Array()', 'arr()', 'createArray()', 'A'),
('Which of the following is a PHP magic constant?', '__LINE__', '__FILE__', '__METHOD__', 'All of the above', 'D'),
('How can you get the current script name in PHP?', '$_SERVER[\'SCRIPT_NAME\']', '$_SERVER[\'PHP_SELF\']', '$_SERVER[\'SCRIPT_FILENAME\']', '$_SERVER[\'SCRIPT\']', 'B'),
('What is the correct way to create a function in PHP?', 'function myFunc()', 'create myFunc()', 'def myFunc()', 'None of the above', 'A'),
('What is the use of the `empty()` function in PHP?', 'Check if a variable is set', 'Check if a variable is empty', 'Check if a variable is null', 'None of the above', 'B'),
('Which function is used to count the number of elements in an array in PHP?', 'size()', 'count()', 'length()', 'sizeof()', 'B'),
('What is the purpose of the `header()` function in PHP?', 'To send HTTP headers', 'To send HTML headers', 'To start a session', 'To include a file', 'A'),
('How do you terminate a script in PHP?', 'exit()', 'die()', 'Both A and B', 'None of the above', 'C'),
('Which keyword is used to define a class in PHP?', 'define', 'class', 'new', 'create', 'B'),
('What is the use of the `var_dump()` function in PHP?', 'Dump the content of a variable', 'Display variable type', 'Display variable value', 'All of the above', 'D'),
('How do you connect to a MySQL database using PDO in PHP?', 'new PDO()', 'pdo_connect()', 'connect_pdo()', 'None of the above', 'A'),
('What is the correct way to end a PHP statement?', '.', ';', ':', 'end', 'B'),
('How can you get the number of characters in a string in PHP?', 'strlen()', 'count()', 'sizeof()', 'length()', 'A'),
('What is the purpose of the `implode()` function in PHP?', 'Split a string into an array', 'Join array elements into a string', 'Find a substring in a string', 'None of the above', 'B'),
('Which function is used to generate a random number in PHP?', 'random()', 'rand()', 'generateRandom()', 'getRandom()', 'B'),
('What is the use of `strip_tags()` function in PHP?', 'Remove spaces from a string', 'Remove HTML and PHP tags from a string', 'Convert tags to string', 'None of the above', 'B'),
('How do you create a cookie in PHP?', 'cookie_set()', 'setcookie()', 'create_cookie()', 'None of the above', 'B'),
('What is the purpose of the `md5()` function in PHP?', 'Encrypt a string', 'Hash a string', 'Generate a random string', 'None of the above', 'B'),
('How can you delete a file in PHP?', 'delete()', 'unlink()', 'remove()', 'None of the above', 'B'),
('What is the output of the following code? echo "Hello " . "World!";', 'Hello World!', 'HelloWorld!', 'Hello . World!', 'Error', 'A'),
('Which function is used to find files in a directory in PHP?', 'find()', 'glob()', 'search()', 'find_files()', 'B'),
('How do you get the length of an array in PHP?', 'array_length()', 'length()', 'count()', 'sizeof()', 'C'),
('What does `PHP_SELF` return?', 'The PHP version', 'The current script', 'The server IP', 'The client IP', 'B'),
('Which function is used to get the current date in PHP?', 'getdate()', 'date()', 'current_date()', 'get_current_date()', 'B'),
('What does the `json_encode()` function do in PHP?', 'Convert an array to a JSON string', 'Decode a JSON string', 'Encode a string', 'None of the above', 'A'),
('How do you define a constant in PHP?', 'const CONSTANT_NAME', 'define(CONSTANT_NAME)', 'constant(CONSTANT_NAME)', 'None of the above', 'B'),
('What is the correct way to open a file in PHP for reading?', 'fopen(file, "r")', 'open(file, "r")', 'read(file)', 'fread(file, "r")', 'A'),
('What is the output of the following code? $a = 1; $b = &$a; $b = 2; echo $a;', '1', '2', 'Error', 'Undefined', 'B'),
('Which function is used to sort an array in PHP?', 'sort()', 'order()', 'arrange()', 'array_sort()', 'A'),
('What is the use of `strpos()` function in PHP?', 'Find the position of a substring in a string', 'Replace a substring', 'Split a string', 'None of the above', 'A'),
('How can you prevent SQL injection in PHP?', 'Using `mysql_query()`', 'Using `mysqli_query()`', 'Using PDO with prepared statements', 'None of the above', 'C'),
('Which of the following is a PHP predefined error reporting constant?', 'E_ALL', 'ERROR_ALL', 'ALL_ERRORS', 'NONE', 'A'),
('What is the default session timeout in PHP?', '20 minutes', '30 minutes', '24 minutes', 'No default', 'B'),
('How can you retrieve data from a form that is submitted using the POST method in PHP?', '$_POST[]', '$_GET[]', '$_REQUEST[]', '$_DATA[]', 'A'),
('Which function is used to redirect a user in PHP?', 'header()', 'redirect()', 'location()', 'move()', 'A'),
('What is the use of the `file_get_contents()` function in PHP?', 'Read a file into a string', 'Write a string to a file', 'Delete a file', 'None of the above', 'A'),
('Which of the following is used to declare a constant in PHP?', 'define()', 'const', 'constant()', 'def()', 'A'),
('Which symbol is used to denote a variable in PHP?', '#', '$', '@', '&', 'B'),
('Which of the following is used to get the length of a string in PHP?', 'strlen()', 'strlength()', 'length()', 'str_len()', 'A'),
('Which function is used to find files in PHP?', 'search()', 'find()', 'glob()', 'locate()', 'C'),
('What is the correct way to open a file in read mode in PHP?', 'fopen($file, "r")', 'open($file, "r")', 'fread($file)', 'file_read($file)', 'A'),
('How do you output text in PHP?', 'print()', 'echo()', 'write()', 'display()', 'B'),
('Which function is used to start a session in PHP?', 'start_session()', 'init_session()', 'session_start()', 'session_init()', 'C'),
('Which of the following is a superglobal variable in PHP?', '$_SESSION', '$GLOBALS', '$_SERVER', 'All of the above', 'D'),
('Which method is used to get form data in PHP?', '$_GET[]', '$_FORM[]', '$_DATA[]', '$_POST[]', 'A'),
('Which of the following is a correct way to connect to a MySQL database in PHP?', 'mysql_connect()', 'mysqli_connect()', 'db_connect()', 'pdo_connect()', 'B'),
('What is the default file extension for PHP files?', '.ph', '.php', '.phtml', '.php5', 'B'),
('Which function is used to include files in PHP?', 'import()', 'include()', 'require()', 'Both B and C', 'D'),
('Which of the following is true about PHP?', 'PHP is an open-source language', 'PHP is a server-side scripting language', 'PHP scripts are executed on the server', 'All of the above', 'D'),
('How do you define a function in PHP?', 'functionName() {}', 'function functionName() {}', 'def functionName() {}', 'func functionName() {}', 'B'),
('What will be the output of the following code: echo 10 % 3;', '0', '1', '2', '3', 'B'),
('Which function is used to check if a file exists in PHP?', 'file_exist()', 'file_exists()', 'is_file()', 'exists()', 'B'),
('Which function is used to return the current timestamp in PHP?', 'now()', 'time()', 'timestamp()', 'current_time()', 'B'),
('How do you create an array in PHP?', 'array = ()', '$array[]', '$array = array()', '$array = []', 'C'),
('Which function is used to remove whitespace from the beginning and end of a string in PHP?', 'trim()', 'strip()', 'clear()', 'cut()', 'A'),
('What will be the output of the following code: echo "5" + 5;', '55', '10', 'Error', 'NaN', 'B'),
('Which of the following is not a PHP data type?', 'Integer', 'String', 'Float', 'Character', 'D'),
('What does isset() function do in PHP?', 'Check if a variable is set and is not NULL', 'Check if a variable is empty', 'Check if a variable is an integer', 'Check if a variable is an array', 'A'),
('Which of the following is used to end a PHP statement?', 'Colon', 'Semicolon', 'Comma', 'Dot', 'B'),
('What will be the output of the following code: echo 5 ** 2;', '25', '10', '7', 'Error', 'A'),
('Which function is used to count the number of elements in an array in PHP?', 'count()', 'size()', 'array_count()', 'elements()', 'A'),
('How do you define a constant in PHP?', 'constant MY_CONSTANT = 10;', 'define("MY_CONSTANT", 10);', 'const MY_CONSTANT = 10;', 'Both B and C', 'D'),
('Which function is used to get the type of a variable in PHP?', 'gettype()', 'type()', 'typeof()', 'var_type()', 'A'),
('What is the output of the following code: echo 3 > 2 ? "Yes" : "No";', '"Yes"', '"No"', '1', 'Error', 'A'),
('How do you create a cookie in PHP?', 'setcookie()', 'create_cookie()', 'makecookie()', 'cookie()', 'A'),
('Which of the following is not a valid PHP variable name?', '$var_name', '$VarName', '$_varName', '$var-name', 'D'),
('Which function is used to sort an array in ascending order in PHP?', 'arr_sort()', 'sort()', 'order()', 'ascend()', 'B'),
('How do you delete an element from an array in PHP?', 'remove()', 'delete()', 'unset()', 'erase()', 'C'),
('What will be the output of the following code: echo 10 == "10";', 'True', 'False', 'Error', '0', 'A'),
('How do you start a comment in PHP?', '//', '/*', '--', '#', 'A'),
('Which function is used to convert a string to lowercase in PHP?', 'strtolower()', 'strlower()', 'tolower()', 'lower()', 'A'),
('What will be the output of the following code: echo 2 + 2 * 2;', '6', '8', '4', '10', 'A'),
('How do you redirect a user to another page in PHP?', 'redirect()', 'header()', 'goto()', 'forward()', 'B'),
('Which of the following is a valid PHP variable name?', '$myVar', '$2var', '$-var', '$var#', 'A'),
('Which function is used to convert an array to a string in PHP?', 'implode()', 'explode()', 'join()', 'merge()', 'A'),
('How do you check if a variable is an array in PHP?', 'is_array()', 'array_check()', 'isarr()', 'check_array()', 'A'),
('Which function is used to generate a random number in PHP?', 'random()', 'rand()', 'generate()', 'randomize()', 'B'),
('What will be the output of the following code: echo strtoupper("hello");', '"hello"', '"HELLO"', '"Hello"', 'Error', 'B'),
('Which function is used to return a part of a string in PHP?', 'substring()', 'substr()', 'slice()', 'sub()', 'B'),
('Which of the following is used to terminate the script execution in PHP?', 'exit()', 'stop()', 'end()', 'terminate()', 'A'),
('How do you check if a value exists in an array in PHP?', 'in_array()', 'array_search()', 'find_in_array()', 'value_exist()', 'A'),
('What will be the output of the following code: echo 10 <=> 20;', '1', '0', '-1', 'Error', 'C'),
('Which of the following is not a PHP loop?', 'for', 'foreach', 'repeat', 'while', 'C'),
('What is the default session timeout in PHP?', '24 minutes', '30 minutes', '1 hour', '20 minutes', 'D'),
('How do you destroy a session in PHP?', 'session_destroy()', 'session_unset()', 'session_delete()', 'destroy_session()', 'A');

